export const CONCEPT_THRESHOLD = 10; // 개념글 승격 기준 추천 수
export const PAGE_SIZE = 20; // 게시글 목록 페이지당 글 수
export const COMMENT_PAGE_SIZE = 50;
export const HIT_THRESHOLD = 20; // 실시간 베스트 기준

export const UNIVERSITY_DOMAINS: Record<string, string> = {
  "snu.ac.kr": "서울대학교",
  "yonsei.ac.kr": "연세대학교",
  "korea.ac.kr": "고려대학교",
  "kaist.ac.kr": "KAIST",
  "postech.ac.kr": "포항공과대학교",
  "skku.edu": "성균관대학교",
  "hanyang.ac.kr": "한양대학교",
  "sogang.ac.kr": "서강대학교",
  "cau.ac.kr": "중앙대학교",
  "khu.ac.kr": "경희대학교",
  "hufs.ac.kr": "한국외국어대학교",
  "uos.ac.kr": "서울시립대학교",
  "konkuk.ac.kr": "건국대학교",
  "dongguk.edu": "동국대학교",
  "sejong.ac.kr": "세종대학교",
  "sungshin.ac.kr": "성신여자대학교",
  "duksung.ac.kr": "덕성여자대학교",
  "sookmyung.ac.kr": "숙명여자대학교",
  "ewha.ac.kr": "이화여자대학교",
  "hongik.ac.kr": "홍익대학교",
  "kookmin.ac.kr": "국민대학교",
  "smu.ac.kr": "상명대학교",
  "kwangwoon.ac.kr": "광운대학교",
  "mju.ac.kr": "명지대학교",
  "sangmyung.kr": "상명대학교",
  "inha.ac.kr": "인하대학교",
  "ajou.ac.kr": "아주대학교",
  "gachon.ac.kr": "가천대학교",
  "dankook.ac.kr": "단국대학교",
  "catholic.ac.kr": "가톨릭대학교",
  "syu.ac.kr": "삼육대학교",
  "tu.ac.kr": "한신대학교",
  "pusan.ac.kr": "부산대학교",
  "knu.ac.kr": "경북대학교",
  "jnu.ac.kr": "전남대학교",
  "chonnam.ac.kr": "전남대학교",
  "cnu.ac.kr": "충남대학교",
  "cbnu.ac.kr": "충북대학교",
  "gnu.ac.kr": "경상국립대학교",
  "kangwon.ac.kr": "강원대학교",
  "jejunu.ac.kr": "제주대학교",
  "jbnu.ac.kr": "전북대학교",
  "kumoh.ac.kr": "금오공과대학교",
  "ut.ac.kr": "한국교통대학교",
  "chungbuk.ac.kr": "충북대학교",
  "hanbat.ac.kr": "한밭대학교",
  "knsu.ac.kr": "한국체육대학교",
  "karts.ac.kr": "한국예술종합학교",
  "unist.ac.kr": "울산과학기술원",
  "gist.ac.kr": "광주과학기술원",
  "dgist.ac.kr": "대구경북과학기술원",
  "suwon.ac.kr": "수원대학교",
  "kyonggi.ac.kr": "경기대학교",
  "hallym.ac.kr": "한림대학교",
  "hannam.ac.kr": "한남대학교",
  "deu.ac.kr": "동의대학교",
  "koreatech.ac.kr": "한국기술교육대학교",
  "ks.ac.kr": "경성대학교",
  "pknu.ac.kr": "부경대학교",
};
